name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: petesouth/shyhumangames-gamefeed
        branch: gh-pages  # This is the branch the action will deploy to
        folder: 3rdparty/spacealiensurvival/dist  # This is the source folder
